# Generated by Django 5.0.6 on 2024-05-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisnik', '0002_workout_exercises_workout_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
    ]
