# Generated by Django 5.0.6 on 2024-05-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisnik', '0003_remove_workout_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', to='Zapisnik.exercise'),
        ),
    ]
