# Generated by Django 5.0.6 on 2024-05-14 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zapisnik', '0004_workout_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='notes',
        ),
    ]
